# -*- coding: utf-8 -*-
"""python project big.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y62evAdnvm6ZwiNWvl-iJqzEA80uMe0Y
"""

print("Welcome to this game of questions!")

gaming = input("Do you want to play this game? ")
print(gaming)

if gaming.lower() != "yes":
  quit()
print("ok ;)")
score = 0

answer = input("What is the powerhouse of the cell? ")
if answer.lower() == "mitochondria":
    print("Correct!")
    score += 1
else:
    print("Wrong answer :(")

answer = input("In which part of the body is the heart located? ")
if answer.lower() == "chest":
    print("Correct!")
    score += 1
else:
    print("Wrong answer :(")

answer = input("Which system is responsible for protecting the body against diseases? ")
if answer.lower() == "immune system":
    print("Correct!")
    score += 1
else:
    print("Wrong answer :(")

answer = input("What is the basic unit of heredity in living organisms? ")
if answer.lower() == "gene":
    print("Correct!")
    score += 1
else:
    print("Wrong answer :(")

answer = input("What is the largest organ in the human body? ")
if answer.lower() == "skin":
    print("Correct!")
    score += 1
else:
    print("Wrong answer :(")

answer = input("Which gas do humans primarily exhale during respiration? ")
if answer.lower() == "co2":
    print("Correct!")
    score += 1
else:
    print("Wrong answer :(")

answer = input("What is the function of the mitochondria in a cell? ")
if answer.lower() == "produce energy":
    print("Correct!")
    score += 1
else:
    print("Wrong answer :(")

print("You got " + str(score) + " questions correct!")

print("You got " + str((score/7) * 100) + "%.")