# -*- coding: utf-8 -*-
"""BMI calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w5PG2F4rupRjo2_gTetnZFsFrnldd56v
"""

def calculate_bmi(weight, height):
    """
    Calculate BMI (Body Mass Index) using the weight (in kilograms) and height (in meters).
    Formula: BMI = weight / (height^2)
    """
    try:
        bmi = weight / (height ** 2)
        return bmi
    except ZeroDivisionError:
        print("Error: Height should be greater than zero.")
        return None

def interpret_bmi(bmi):
    """
    Interpret BMI and provide a general category.
    """
    if bmi is None:
        return "Invalid input"
    elif bmi < 18.5:
        return "Underweight"
    elif 18.5 <= bmi < 25:
        return "Normal weight"
    elif 25 <= bmi < 30:
        return "Overweight"
    else:
        return "Obese"

def main():
    try:
        weight = float(input("Enter your weight in kilograms: "))
        height = float(input("Enter your height in meters: "))
    except ValueError:
        print("Error: Please enter valid numerical values for weight and height.")
        return

    bmi = calculate_bmi(weight, height)
    if bmi is not None:
        category = interpret_bmi(bmi)
        print(f"Your BMI is {bmi:.2f}, which is considered {category}.")

if __name__ == "__main__":
    main()