# -*- coding: utf-8 -*-
"""Choose your own adventure <3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HIIPPAns0KxWUrWYJhhJipgIJZaGBWHH
"""

name = input("Type your name: ")
print("Welcome", name, "to this adventure!")
answer = input("You are on a dirt road, it has come to an end and you can go left or right. Which way would you like to go? ").lower()

if answer == "left":
  answer = input("You come to a river, you can walk around it or swim across? Type walk to walk around and swim to swim across: ")
  if answer == "swim":
    print("You swam across and were eaten by an alligator.")
  elif answer == "walk":
    print("You walked for many miles, ran out of water and you lost the game.")
  else:
    print("Not a valid option. You lose")



if answer == "right":
  answer = input("You come to a bridge, it looks wobbly, do you want to cross it or head back (cross/back)? ")
  if answer == "cross":
    answer = input("You cross the bridge and meet a stranger. Do you talk to him (yes/no)? ")
    if answer == "yes":
       print("You talk to the stranger and he gives you gold. You WIN!!!")
    elif answer == "no":
      print("You ignore the stranger and he is offended and you lose...")
    else:
       print("Not a valid option. You lose")

  elif answer == "back":
    print("You go back to the main road and lose.")
  else:
    print("Not a valid option. You lose")

print("Thank you for trying", name, "!")
